
version: '3.9'

services:
  client:
    build: client/
    ports: 
      - '8080:5000'
    depends_on:
      - 'backend'

  backend:
    build: backend/
    ports:
      - '5000:5000'
    # depends_on:
    #   - 'database'

  # database:
  #   image: mysql